/**
 * Seed strategi yang sudah dikalibrasi dengan data pasar Robinhood Chain
 * (DexScreener n≈50 token, Blockscout holders sering 0).
 *
 * Prinsip "aman":
 * - min_holders 0 (data holder belum reliable)
 * - min_saved_wallet_holders 0 sampai user /walletadd
 * - require_security_pass false + max_security_risk terkontrol
 * - min_volume / txns realistis (bukan 25k yang menolak 98% pasar)
 * - llm_min_confidence per strategi (bukan global 75)
 */

export const STRATEGY_SEEDS = {
  sniper: {
    entry_mode: 'immediate',
    min_source_count: 2,
    require_volume_spike: true,
    pool_age_max_ms: 7 * 86400_000,
    min_mcap_usd: 5000,
    max_mcap_usd: 800000,
    min_liquidity_usd: 8000,
    min_volume_h24_usd: 2000,
    min_txns_h24: 15,
    min_holders: 0,
    max_top10_holder_percent: 70,
    max_ath_distance_pct: 0,
    trending_min_volume_usd: 1000,
    max_rug_score: 0.55,
    require_security_pass: false,
    max_security_risk: 0.6,
    min_saved_wallet_holders: 0,
    max_insider_count: 5,
    max_sniper_share_percent: 40,
    position_size_eth: 0.03,
    max_open_positions: 5,
    tp_percent: 50,
    sl_percent: -25,
    trailing_enabled: true,
    trailing_percent: 20,
    partial_tp: false,
    partial_tp_at_percent: 0,
    partial_tp_sell_percent: 0,
    max_hold_ms: 0,
    use_llm: true,
    llm_min_confidence: 55,
  },

  dip_buy: {
    entry_mode: 'wait_for_dip',
    min_source_count: 1,
    require_volume_spike: false,
    pool_age_max_ms: 30 * 86400_000,
    min_mcap_usd: 15000,
    max_mcap_usd: 3000000,
    min_liquidity_usd: 15000,
    min_volume_h24_usd: 2000,
    min_txns_h24: 15,
    min_holders: 0,
    max_top10_holder_percent: 70,
    max_ath_distance_pct: -30,
    trending_min_volume_usd: 0,
    max_rug_score: 0.55,
    require_security_pass: false,
    max_security_risk: 0.6,
    min_saved_wallet_holders: 0,
    max_insider_count: 5,
    max_sniper_share_percent: 35,
    position_size_eth: 0.03,
    max_open_positions: 5,
    tp_percent: 35,
    sl_percent: -20,
    trailing_enabled: true,
    trailing_percent: 15,
    partial_tp: false,
    partial_tp_at_percent: 0,
    partial_tp_sell_percent: 0,
    max_hold_ms: 0,
    use_llm: true,
    llm_min_confidence: 55,
  },

  smart_money: {
    entry_mode: 'immediate',
    min_source_count: 2,
    require_volume_spike: false,
    pool_age_max_ms: 30 * 86400_000,
    min_mcap_usd: 10000,
    max_mcap_usd: 5000000,
    min_liquidity_usd: 10000,
    min_volume_h24_usd: 3000,
    min_txns_h24: 30,
    min_holders: 0,
    max_top10_holder_percent: 55,
    max_ath_distance_pct: 0,
    trending_min_volume_usd: 2000,
    max_rug_score: 0.5,
    require_security_pass: false,
    max_security_risk: 0.5,
    min_saved_wallet_holders: 0,
    max_insider_count: 3,
    max_sniper_share_percent: 30,
    position_size_eth: 0.02,
    max_open_positions: 10,
    tp_percent: 100,
    sl_percent: -25,
    trailing_enabled: false,
    trailing_percent: 0,
    partial_tp: true,
    partial_tp_at_percent: 100,
    partial_tp_sell_percent: 50,
    max_hold_ms: 0,
    use_llm: true,
    llm_min_confidence: 60,
  },

  degen: {
    entry_mode: 'immediate',
    min_source_count: 1,
    require_volume_spike: false,
    pool_age_max_ms: 7 * 86400_000,
    min_mcap_usd: 0,
    max_mcap_usd: 400000,
    min_liquidity_usd: 2500,
    min_volume_h24_usd: 500,
    min_txns_h24: 5,
    min_holders: 0,
    max_top10_holder_percent: 85,
    max_ath_distance_pct: 0,
    trending_min_volume_usd: 0,
    max_rug_score: 0.8,
    require_security_pass: false,
    max_security_risk: 0.85,
    min_saved_wallet_holders: 0,
    max_insider_count: 10,
    max_sniper_share_percent: 50,
    position_size_eth: 0.02,
    max_open_positions: 10,
    tp_percent: 35,
    sl_percent: -15,
    trailing_enabled: true,
    trailing_percent: 12,
    partial_tp: false,
    partial_tp_at_percent: 0,
    partial_tp_sell_percent: 0,
    max_hold_ms: 2 * 3600_000,
    use_llm: false,
    llm_min_confidence: 0,
  },
};

export const STRATEGY_META = {
  sniper: { name: 'Sniper', enabled: 1 },
  dip_buy: { name: 'Dip Buy', enabled: 0 },
  smart_money: { name: 'Smart Money', enabled: 0 },
  degen: { name: 'Degen', enabled: 0 },
};
